<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE contactos [
  <!ELEMENT contactos (contacto)>
  <!ELEMENT contacto (nombreCompleto, localizacion, telefono, conoce, descripcion)>
  
  <!ELEMENT nombreCompleto (nombre, primerApellido, segundoApellido)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT primerApellido (#PCDATA)>
  <!ELEMENT segundoApellido (#PCDATA)>

  <!ELEMENT localizacion (direccion | (latitud, longitud))>
  <!ELEMENT direccion (#PCDATA)>
  <!ELEMENT latitud (#PCDATA)>
  <!ELEMENT longitud (#PCDATA)>

  <!ELEMENT telefono (#PCDATA)>

  <!ELEMENT conoce (#PCDATA)>

  <!ELEMENT descripcion (#PCDATA | em | strong | br)*>
  <!ELEMENT em (#PCDATA)>
  <!ELEMENT strong (#PCDATA)>
  <!ELEMENT br EMPTY>
]>
<contactos>
  <contacto>
    <nombreCompleto>
      <nombre>Fulanito</nombre>
      <primerApellido>Perez</primerApellido>
      <segundoApellido>Diaz</segundoApellido>
    </nombreCompleto>
    <localizacion>
      <latitud>50.7219</latitud>
      <longitud>-3.533617</longitud>
    </localizacion>
    <telefono>99555666777</telefono>
    <conoce>Menganito Lopez, Zutanito Garcia</conoce>
    <descripcion>
      Fulanito es un estudiante de ASIX y creador de la 
      <em>primera version</em><br />
      A Fulanito le <strong>encanta</strong> XML!
    </descripcion>
  </contacto>
</contactos>

