=== rafapuig/1415-ASIX-1-LGI/LGI/LGI-XSD/Contactos3.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema id="Contactos"
    targetNamespace="http://tempuri.org/Contactos.xsd"
    elementFormDefault="qualified"
    xmlns:contactos="http://tempuri.org/Contactos.xsd"    
    xmlns="http://www.w3.org/2001/XMLSchema">

  <element name="nombre" type="string" />
  <element name="primerApellido" type="string" />
  <element name="segundoApellido" type="string" />

  <group name="NombreGroup">
    <sequence>
      <element ref="contactos:nombre" maxOccurs="2" />
      <element ref="contactos:primerApellido" />
      <element ref="contactos:segundoApellido" minOccurs="0" />
    </sequence>
  </group>

  <complexType name="NombreType">
    <group ref="contactos:NombreGroup" />
    <attribute name="titulo" type="string" />
  </complexType>

  <complexType name="LocalizacionType">
    <choice minOccurs="0" maxOccurs="unbounded">
      <element name="direccion" type="string" />
      <sequence>
        <element name="latitud" type="float" />
        <element name="longitud" type="float" />        
      </sequence>      
    </choice>    
  </complexType>
  
  <complexType name="ConoceType">
    <attribute name="contactos" type="IDREFS" />
  </complexType>
  
  <complexType name="DescripcionType" mixed="true">
    <choice minOccurs="0" maxOccurs="unbounded">
      <element name="em" type="string" />
      <element name="strong" type="string" />
      <element name="br" type="string" />
    </choice>
  </complexType>
  
  <attributeGroup name="contactosAttributes">
    <attribute name="version" type="decimal" fixed="1.0" />
    <attribute name="origen" type="string" />
  </attributeGroup>

  <complexType name="TelefonoType">
    <simpleContent>
      <extension base="string">
        <attribute name="tipo" default="Casa">
          <simpleType>
            <restriction base="string">
              <enumeration value="Casa"/>
              <enumeration value="Trabajo"/>
              <enumeration value="Movil"/>
              <enumeration value="Fax"/>
            </restriction>
          </simpleType>
        </attribute>
      </extension>
    </simpleContent>
  </complexType>


  <element name="contactos">
    <complexType>
      <sequence>
        <element name="contacto" minOccurs="0" maxOccurs="unbounded">
          <complexType>
            <sequence>
              <element name="nombreCompleto" type="contactos:NombreType" />
              <element name="localizacion" type="contactos:LocalizacionType" />
              <element name="telefono" type="contactos:TelefonoType" />
              <element name="conoce" type="contactos:ConoceType" />
              <element name="descripcion" type="contactos:DescripcionType" />
            </sequence>
            <attribute name="etiquetas" type="token" />
            <attribute name="persona" type="ID" />
          </complexType>
        </element>
      </sequence>
      <attributeGroup ref="contactos:contactosAttributes" />
    </complexType>
  </element>
  
</schema>

=== rafapuig/1415-ASIX-1-LGI/LGI/LGI-XSD/Contactos3.xml
<?xml version="1.0" encoding="utf-8" ?>
<contactos xmlns="http://tempuri.org/Contactos.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://tempuri.org/Contactos.xsd Contactos3.xsd"
           version="1.0" origen="LGI XML Tema 4 - Esquemas XSD">
  
  <contacto persona="Fulanito_Perez" etiquetas="escritor xml estudiante">
    <nombreCompleto>
      <nombre>Fulanito</nombre>
      <primerApellido>Perez</primerApellido>
      <segundoApellido>Martin</segundoApellido>      
    </nombreCompleto>
    <localizacion>
      <direccion>Calle de los Olmos, 23 - Madrid</direccion>
      <latitud>50.7218</latitud>
      <longitud>-3.533617</longitud>      
    </localizacion>
    <telefono tipo="Trabajo">000-111-222-333</telefono>
    <conoce contactos="Menganito_Lopez"/>
    <descripcion>
      Fulanito es un estudiante de ASIX y creador de la <em>primera version</em><br />
      A Fulanito le <strong>encanta</strong> XML!
    </descripcion>
  </contacto>
  
  <contacto persona="Menganito_Lopez" etiquetas="escritor consultor senior">
    <nombreCompleto>
      <nombre>Menganito</nombre>
      <primerApellido>Lopez</primerApellido>
    </nombreCompleto>
    <localizacion>
      <direccion>Paradero desconocido</direccion>
    </localizacion>
    <telefono tipo="Casa">555-777-999</telefono>
    <conoce contactos="Fulanito_Perez Zutanito_Garcia" />
    <descripcion>Consultor Tecnico Senior, se tituló en ASIX hace unos años</descripcion>
  </contacto>
  
  <contacto persona="Zutanito_Garcia" etiquetas="xml esquemas experto">
    <nombreCompleto>
      <nombre>Zutanito</nombre>
      <nombre>Garcia</nombre>
      <primerApellido>Rodriguez</primerApellido>
    </nombreCompleto>
    <localizacion>
      <direccion>Paradero desconocido</direccion>
      <latitud>34.445454</latitud>
      <longitud>-4.345</longitud>
    </localizacion>
    <telefono>565-747-989</telefono>
    <conoce/>
    <descripcion>Consultor Tecnico Senior, se tituló en ASIX hace unos años</descripcion>
  </contacto>  

</contactos>
